export const INIT_CATEGORIES = 'INIT_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const OPERATION_START = 'OPERATION_START';
export const OPERATION_FAIL = 'OPERATION_FAIL';

export const SEARCHING_START = 'SEARCHING_START';
export const SEARCHING_FAIL = 'SEARCHING_FAIL';
export const SEARCHING_SUCCESS = 'SEARCHING_SUCCESS';
export const SEARCHING_INIT = 'SEARCHING_INIT';

export const SEARCHING_UPDATE_ITEM = 'SEARCHING_UPDATE_ITEM';
export const SEARCHING_REMOVE_ITEM = 'SEARCHING_REMOVE_ITEM';

export const SAVE_DOC_SUCCESS = 'SAVE_DOC_SUCCESS';
export const DELETE_DOC_SUCCESS = 'DELETE_DOC_SUCCESS';
export const INIT_DOC = 'INIT_DOC';

export const SAVE_NEWS_SUCCESS = 'SAVE_NEWS_SUCCESS';
export const INIT_NEWS = 'INIT_NEWS';
